# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coworking In Cameroon
email: coworkingcameroon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Find coworking spaces in Douala, Yaounde and Kribi
baseurl: "/coworking" # the subpath of your site, e.g. /blog
spaces_img_url: "/coworking/images/spaces/"
url: "http://coworkingcameroon.github.io" # the base hostname & protocol for your site
twitter_username: coworkingcameroon
facebook_page: coworkingcameroon
github_username: coworkingcameroon

# Build settings
markdown: kramdown
